export { AppRoutes } from './AppRoutes';
export {
	CATALOGO,
	LOGIN,
	INICIO,
	VETSANLOR,
	SERVICIOS,
	LINKS_NAV_APP,
	USER_PERFIL,
	USER_HOME,
	MEDICO_INICIO,
	MEDICO_TAREAS,
	MEDICO_MASCOTAS,
	MEDICO_CATALOGO,
	MEDICO_CITAS,
	MASCOTA_HISTORIAL,
	FORBIDDEN,
	UNAUTHORIZED,
} from './link';
